version: "3.4"
services:
  curso-beta-pagamentos:
    container_name: curso-beta-pagamentos
    build: ./
    volumes:
      - ./src/:/usr/src
      - /usr/src/xray-daemon
      - /usr/src/curso-beta-pagamentos
    environment:
      - PORT=80
      - DB_HOST=curso-beta-dev.clymltjuqpw4.us-east-1.rds.amazonaws.com
      - DB_USER=master
      - DB_PASS=mudar123
      - DB_NAME=curso-beta-pagamento
      - EAD_URL=https://ead-dev.cursobeta.com.br
      - URL_POST_BACK=https://dev-curso-beta-pagamentos.cursobeta.com.br/postBack
    ports:
      - 80:80
    command: npm run deploy
    networks:
      - cbpg-network
networks:
  cbpg-network:
    driver: bridge
