version: "3.4"
services:
  curso-beta-pagamentos:
    container_name: curso-beta-pagamentos
    build: ./
    volumes:
      - ./src/:/usr/src
      - /usr/src/xray-daemon
      - /usr/src/curso-beta-pagamentos
    environment:
      - PORT=80
    ports:
      - 80:80
    command: npm run deploy
    networks:
      - cbpg-network
networks:
  cbpg-network:
    driver: bridge
